system:
  log_level: INFO
  pid_file: anomaly_detector.pid
  max_restarts: 3
capture:
  interface: eth0
  bpf_filter: ''
  buffer_size: 1048576
  snaplen: 65535
  promiscuous: false
session:
  timeout: 300
  max_packets_per_session: 1000
  cleanup_interval: 60
features:
  enabled_stat_features:
  - packet_size
  - protocol
  - payload_size
  - tcp_flags
  - udp_length
  - icmp_type
  temporal_window_size: 60
  temporal_window_step: 10
detection:
  threshold: 0.8
  alert_email: ''
  smtp_server: smtp.example.com
  smtp_port: 587
  smtp_username: ''
  smtp_password: ''
training:
  check_interval: 3600
  min_samples: 1000
  test_size: 0.2
  cross_validation_folds: 5
  retrain_threshold: 0.05
model:
  type: xgboost
  save_interval: 3600
  max_versions: 10
