xgboost:
  n_estimators: 100
  max_depth: 5
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  objective: binary:logistic
  eval_metric: logloss
random_forest:
  n_estimators: 100
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  n_jobs: -1
lstm:
  input_dim: 10
  hidden_dim: 32
  output_dim: 1
  num_layers: 2
  dropout: 0.2
  learning_rate: 0.001
  batch_size: 32
  epochs: 10
